homepage:
    path: /{_locale}
    controller: App\Controller\BlogController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: blog/index.html.twig
        _locale: '%locale%'
        page: 1
        _format: html

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

